### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/purchase-workflow#1585]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] partner_supplierinfo_smartbutton - By @victoralmau - #2324
- [x] procurement_purchase_no_grouping - By @victoralmau - #2186
- [x] product_form_purchase_link - By @aliciagaarzo - #1890 - Now is in Odoo Standard 
- [x] product_supplierinfo_qty_multiplier - By @legalsylvain - #2122
- [x] purchase_advance_payment - By @sonhd91 - #1702
- [x] purchase_analytic_global - By @sistecem - #2393
- [ ] purchase_blanket_order
- [ ] purchase_default_terms_conditions
- [ ] purchase_delivery_split_date
- [ ] purchase_deposit
- [x] purchase_discount - By @ramiadavid - #1602
- [ ] purchase_exception
- [x] purchase_force_invoiced - By @alexis-via - #1681
- [x] purchase_invoice_plan - By @AungKoKoLin1997 - #1982
- [x] purchase_landed_cost - By @carolinafernandez-tecnativa - #2219
- [x] purchase_last_price_info - By @AMhadhbi - #1599
- [ ] purchase_location_by_line
- [x] purchase_manual_delivery - By @PauBForgeFlow - #1985
- [x] purchase_minimum_amount - By @etobella - #2567
- [x] purchase_order_general_discount - By @cuongnmtm - #1889
- [x] purchase_order_line_deep_sort - By @BhaveshHeliconia - #2470
- [ ] purchase_order_line_menu
- [ ] purchase_order_line_packaging_qty - By @rousseldenis - #1672
- [x] ~~purchase_order_line_price_history~~ Included in core
- [x] purchase_order_line_sequence - By @AungKoKoLin1997 - #1961
- [x] purchase_order_line_stock_available - By @victoralmau - #2327
- [x] purchase_order_no_zero_price - By @dsolanki-initos - #1836
- [x] purchase_order_price_recalculation - By @victoralmau - #2187
- [x] purchase_order_product_attachment_mgmt - By @victoralmau - #2190
- [x] purchase_order_product_recommendation - By @Yadier-Tecnativa - #1861
- [x] purchase_order_qty_change_no_recompute - By @victoralmau - #2193
- [x] purchase_order_secondary_unit - By @dalonsod - #2216
- [x] purchase_order_supplier_return - By @AungKoKoLin1997 - #2784
- [x] purchase_order_supplierinfo_update - By @Yadier-Tecnativa - #1864
- [ ] purchase_order_type - By @ChristianSantamaria - #1894
- [x] purchase_order_uninvoiced_amount - By @Yadier-Tecnativa - #1865
- [x] purchase_order_weight_volume - By @tuantrantg - #1972
- [ ] purchase_partner_incoterm
- [x] purchase_partner_selectable_option - By @AungKoKoLin1997 - #2157
- [ ] ~~purchase_picking_state~~ - By @manuelregidor - #2081 --> Deprecated. See the comments in the PR for more information
- [ ] purchase_quick - By @PavarunCh - #1872
- [ ] purchase_receipt_expectation
- [ ] purchase_receipt_expectation_manual
- [ ] purchase_receipt_expectation_manual_split
- [ ] purchase_reception_notify
- [ ] purchase_request
- [x] purchase_request_department - By @mav-adhoc - #2373
- [x] purchase_request_tier_validation - By @imarulbala - #1671
- [x] purchase_requisition_tier_validation - By @dzungtran89 - #1738
- [x] purchase_return - By @PauBForgeFlow - #1975
- [x] purchase_security - By @dalonsod - #1902
- [x] purchase_stock_price_unit_sync - By @AungKoKoLin1997 - #2137
- [x] purchase_tag - By @flalexg - #1888
- [x] purchase_tier_validation - By @imarulbala - #1669
- [x] purchase_warn_message - By @manuelregidor - #2092
- [x] sale_purchase_force_vendor - By @joepsanders - #1966

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by tewtawat** [comment]
Im working on purchase_request migration https://github.com/OCA/purchase-workflow/pull/1592

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working on:
`pruchase_discount` #1602 
`purchase_triple_discount` #1601

**Comment by imarulbala** [comment]
Migration to version 16.0

- purchase_tier_validation https://github.com/OCA/purchase-workflow/pull/1669

**Comment by imarulbala** [comment]
Migration to version 16.0

- purchase_request_tier_validation https://github.com/OCA/purchase-workflow/pull/1671

**Comment by nileshsheliya** [comment]
Migration to version 16.0

- purchase_order_line_price_history https://github.com/OCA/purchase-workflow/pull/1674

**Comment by sonhd91** [comment]
`purchase_advance_payment` :

* https://github.com/OCA/purchase-workflow/pull/1701

**Comment by dzungtran89** [comment]
- https://github.com/OCA/purchase-workflow/pull/1738

**Comment by quannguyen1560** [comment]
Migration to version 16.0

- purchase_default_terms_conditions https://github.com/OCA/purchase-workflow/pull/1709

**Comment by RodrigoBM** [comment]
Im working in purchase_force_invoiced

**Comment by augusto-weiss** [comment]
mig purchase_all_shipments #1710 - This module is not listed

**Comment by CRogos** [comment]
product_form_purchase_link https://github.com/OCA/purchase-workflow/pull/1762 , but I think this module is not needed anymore.

**Comment by aliciagaarzo** [comment]
Im working on purchase_exception https://github.com/OCA/purchase-workflow/pull/1770

**Comment by rolandojduartem** [comment]
I am working on purchase_order_approved to 16.0

**Comment by lehoangan** [comment]
- purchase_line_procurement_group: [#1806](https://github.com/OCA/purchase-workflow/pull/1806)

**Comment by dsolanki-initos** [comment]
purchase_reception_notify

**Comment by vib-adhoc** [comment]
Migration to version 16.0 
- purchase_stock_tier_validation [1874](https://github.com/OCA/purchase-workflow/pull/1874) 
This module is not listed

**Comment by santostelmo** [comment]
Migrating purchase_invoice_plan

**Comment by cuongnmtm** [comment]
I am working on purchase_order_general_discount https://github.com/OCA/purchase-workflow/pull/1889

This module is not listed.

**Comment by aliciagaarzo** [comment]
Im working on purchase_order_qty_change_no_recompute https://github.com/OCA/purchase-workflow/pull/1886

**Comment by pausanchezqubiq** [comment]
Working on purchase_analytic_global

**Comment by flalexg** [comment]
Migration purchase_merge to v16 https://github.com/OCA/purchase-workflow/pull/1887

**Comment by flalexg** [comment]
Migration purchase_tag to v16 https://github.com/OCA/purchase-workflow/pull/1888

**Comment by jaenbox** [comment]
Working on purchase_order_line_menu

**Comment by jaenbox** [comment]
Migration to v16.0 
purchase_partner_selectable_option: [ [16.0][MIG] purchase_partner_selectable_option #1893 ](https://github.com/OCA/purchase-workflow/pull/1893)

**Comment by pausanchezqubiq** [comment]
Working on purchase_partner_incoterm

**Comment by JanQubiQ** [comment]
Working on purchase_request_department https://github.com/OCA/purchase-workflow/pull/1892

**Comment by aliciagaarzo** [comment]
Im working on  product_form_purchase_link https://github.com/OCA/purchase-workflow/pull/1890

**Comment by flalexg** [comment]
Working on purchase_quick

**Comment by dsolanki-initos** [comment]
> Working on purchase_partner_incoterm

Hello @pausanchezqubiq, For this module already PR created. https://github.com/OCA/purchase-workflow/pull/1835

**Comment by aliciagaarzo** [comment]
Im working on purchase_cancel_confirm https://github.com/OCA/purchase-workflow/pull/1895

**Comment by flalexg** [comment]
Working on purchase_total_ordered_qty

**Comment by martiqubiq** [comment]
working on purchase_receipt_expectation

**Comment by dsolanki-initos** [comment]
> purchase_receipt_expectation

Hi @martiqubiq, PR is already created for purchase_receipt_expectation. https://github.com/OCA/purchase-workflow/pull/1903

**Comment by martiqubiq** [comment]
working on purchase_order_line_menu

**Comment by martiqubiq** [comment]
working on purchase_receipt_expectation_manual

**Comment by JanQubiQ** [comment]
working on purchase_receipt_expectation_manual_split https://github.com/OCA/purchase-workflow/pull/1906

**Comment by dsolanki-initos** [comment]
> working on purchase_receipt_expectation_manual

Hello @martiqubiq, I've already migrated the listed module from this repo, I'll create PR of the same today.
purchase_reception_notify, https://github.com/OCA/purchase-workflow/pull/1909
purchase_blanket_order, https://github.com/OCA/purchase-workflow/pull/1908
purchase_receipt_expectation_manual  https://github.com/OCA/purchase-workflow/pull/1907

**Comment by martiqubiq** [comment]
hello @dsolanki-initos , my PR is created since yesterday!

**Comment by joepsanders** [comment]
I'm working on sale_purchase_force_vendor, but it's missing on the list?

**Comment by pedrobaeza** [comment]
When you have the PR, we launch a bot command for adding and linking it here.

**Comment by CLaurelB** [comment]
Working on purchase_order_archive

**Comment by HaraldPanten** [comment]
Manually updated migration issue due to deprecation of purchase_picking_state module. See conversation in https://github.com/OCA/purchase-workflow/pull/2081 for more details.

**Comment by rousseldenis** [comment]
I will migrate purchase_order_price_recalculation

UPDATE: In fact I think there is no need of that one. Updating the limit order date on PO is updating all lines

**Comment by phutungthanhlong** [comment]
purchase_order_line_sequence - this module is not listed, please help! Thanks

**Comment by AungKoKoLin1997** [comment]
purchase_order_line_sequence:

- [[16.0][MIG] purchase_order_line_sequence: Migration to 16.0 #1961](https://github.com/OCA/purchase-workflow/pull/1961)

**Comment by phutungthanhlong** [comment]
purchase_product_multi_add - this module is not listed, it's similar to sale_product_multi_add. I am incapable of coding therefore I'm seeking for help from the community. Thanks

**Comment by MarwanBHL** [comment]
purchase_receipt_percentage #2284

**Comment by sistecem** [comment]
I want to migrate purchase_analytic_global

**Comment by sistecem** [comment]
> I want to migrate purchase_analytic_global
https://github.com/OCA/purchase-workflow/pull/2393

**Comment by BhaveshHeliconia** [comment]
Migrated module 
purchase_order_line_deep_sort : [#2470](https://github.com/OCA/purchase-workflow/pull/2470)
purchase_reception_status_line : [#2520](https://github.com/OCA/purchase-workflow/pull/2520)
