### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/purchase-workflow#193]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] framework_agreement
- [ ] mrp_smart_purchase
- [ ] procurement_batch_generator #204
- [x] product_by_supplier - By @leemannd - #282 
- [ ] product_supplierinfo_discount - By @jweste - #272
- [ ] purchase_all_shipments
- [ ] purchase_analytic_global #228
- [ ] purchase_delivery_address
- [ ] purchase_delivery_split_date
- [ ] purchase_delivery_term
- [ ] purchase_discount - https://github.com/OCA/purchase-workflow/pull/214
- [x] purchase_fiscal_position_update - By @angelmoya - #281 
- [ ] purchase_group_hooks
- [ ] purchase_group_orders
- [ ] purchase_landed_costs
- [ ] purchase_last_price_info
- [ ] purchase_multi_picking
- [ ] purchase_order_force_number
- [ ] purchase_order_reorder_lines
- [ ] purchase_order_revision
- [x] purchase_order_type - @cubells - #310 
- [ ] purchase_origin_address
- [ ] purchase_partial_invoicing
- [ ] purchase_partner_invoice_method
- [ ] purchase_picking_state - By @chafique-delli - #219
- [ ] purchase_requisition_auto_rfq
- [ ] purchase_requisition_auto_rfq_bid_selection
- [ ] purchase_requisition_bid_selection
- [ ] purchase_requisition_delivery_address
- [ ] purchase_requisition_multicurrency
- [ ] purchase_requisition_transport_document
- [ ] purchase_rfq_bid_workflow
- [ ] purchase_rfq_number - By @mikevhe18 - #300 
- [ ] purchase_transport_document
- [ ] vendor_consignment_stock

**Comment by yvaucher** [comment]
Added port of account_analytic_global (from 7.0]

**Comment by jweste** [comment]
Hi, I will have a look into product_supplierinfo_discount.

**Comment by pedrobaeza** [comment]
@jweste, assigned in the main description

**Comment by leemannd** [comment]
@pedrobaeza Hello, you'll find a port of the product_by_supplier in [this PR](https://github.com/OCA/purchase-workflow/pull/282)
