### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/purchase-workflow#279]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] framework_agreement
- [ ] mrp_smart_purchase
- [ ] procurement_batch_generator - By @alexis-via - #483 
- [x] procurement_purchase_no_grouping - By @sergio-teruel - #448 
- [x] product_by_supplier - By @lreficent - #361 
- [x] product_supplierinfo_discount - By @stefanrijnhart - #407
- [ ] purchase_all_shipments
- [ ] purchase_delivery_address
- [ ] purchase_delivery_term
- [x] purchase_discount - By @alexis-via - #316 
- [x] purchase_fiscal_position_update - By @alexis-via - #280 
- [ ] purchase_group_hooks
- [ ] purchase_group_orders
- [x] purchase_landed_costs - By @Roodin - https://github.com/OCA/purchase-workflow/pull/409
- [ ] purchase_last_price_info - ~~By @kittiu - #406~~ By @Abranes - #587 
- [ ] purchase_multi_picking
- [ ] purchase_order_force_number
- [ ] purchase_order_line_description - By @cubells - #488 
- [ ] purchase_order_reorder_lines
- [x] purchase_order_revision - By @cubells - #418 
- [ ] purchase_order_type - By @kikosanchez - #403 
- [ ] purchase_origin_address
- [ ] purchase_partial_invoicing
- [ ] purchase_partner_invoice_method
- [x] purchase_picking_state - By @EBII - #324
- [x] purchase_request - By @adrienpeiffer - #286 
- [ ] purchase_request_to_rfq - By @adrienpeiffer - #287 
- [ ] purchase_request_procurement
- [ ] purchase_requisition_auto_rfq
- [ ] purchase_requisition_auto_rfq_bid_selection
- [ ] purchase_requisition_bid_selection
- [ ] purchase_requisition_delivery_address
- [ ] purchase_requisition_multicurrency
- [ ] purchase_requisition_transport_document
- [ ] purchase_rfq_bid_workflow
- [ ] purchase_transport_document
- [ ] vendor_consignment_stock
- [ ] purchase_tier_validation

**Comment by fmdl** [comment]
purchase_picking_state is done : https://github.com/OCA/purchase-workflow/pull/324

**Comment by pedrobaeza** [comment]
Added!

**Comment by blutecsolutions** [comment]
Is there any news on **purchase_order_variant_mgmt** for v10.0 ?
https://www.odoo.com/apps/modules/9.0/purchase_order_variant_mgmt/
Thanks

**Comment by pedrobaeza** [comment]
No, but it's very easy to do following the sale one.

**Comment by pedrobaeza** [comment]
Note that this module should be moved to OCA/product-variant

**Comment by kittiu** [comment]
migrated, **purchase_last_price_info**, #406
