### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/purchase-workflow#461]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] framework_agreement
- [ ] mrp_smart_purchase
- [ ] procurement_batch_generator
- [x] procurement_purchase_no_grouping - By @carlosdauden - #563
- [x] ~~product_by_supplier - By @lreficent - #596~~ Finally not needed as it's included in core
- [x] product_supplierinfo_discount - ~~By @DarkoNikolovski - #534~~ - By @cubells - #592 
- [ ] purchase_all_shipments - By @mpanarin - #573
- [ ] purchase_allowed_product - By @hieulucky111 - #475 
- [ ] purchase_commercial_partner - By @andreasdsp - #553 
- [x] purchase_date_planned_manual - By @lreficent - #597
- [ ] purchase_delivery_address
- [x] purchase_delivery_split_date - ~~By @hizbul25 - #511~~ By @jbeficent - #584
- [ ] purchase_delivery_term
- [x] purchase_discount - By @pedrobaeza - #470 
- [ ] purchase_fiscal_position_update
- [ ] purchase_fop_shipping
- [ ] purchase_group_hooks
- [ ] purchase_group_orders
- [x] purchase_landed_cost - By @pedrobaeza - #600 
- [ ] purchase_last_price_info - By @celm1990 - #540
- [x] purchase_location_by_line - By @hveficent - #604
- [x] purchase_minimum_amount - By @rgarnau - #477
- [ ] purchase_multi_picking
- [x] purchase_open_qty - ~~By @andreasdsp - #554~~ By @mreficent - #602
- [x] purchase_order_approval_block - By @jbeficent - #480
- [x] purchase_order_approved - By @lreficent - #555
- [ ] purchase_order_force_number
- [x] purchase_order_line_description - By @cubells - #620 
- [ ] purchase_order_reorder_lines
- [ ] purchase_order_revision - By @Montxu - #621 
- [ ] purchase_order_type
- [ ] purchase_origin_address
- [ ] purchase_partial_invoicing
- [ ] purchase_partner_invoice_method
- [ ] purchase_picking_state - By @celm1990 - #546 
- [x] purchase_request - By @jbeficent - #544
- [ ] purchase_request_department - By @hveficent - #598
- [x] purchase_request_procurement -> purchase_request - By @jbeficent - #544
- [x] purchase_request_to_procurement -> purchase_request - By @jbeficent - #544
- [x] purchase_request_to_rfq -> purchase_request - By @jbeficent - #544
- [ ] purchase_request_to_rfq_order_approved > purchase_request_order_approved - By @hveficent - #599
- [ ] purchase_requisition_auto_rfq
- [ ] purchase_requisition_auto_rfq_bid_selection
- [ ] purchase_requisition_bid_selection
- [ ] purchase_requisition_delivery_address
- [ ] purchase_requisition_multicurrency
- [ ] purchase_requisition_transport_document
- [ ] purchase_rfq_bid_workflow
- [x] purchase_tier_validation - By @lreficent - #548
- [ ] purchase_transport_document
- [ ] purchase_triple_discount - ~~By @sferket - #595 - By @krunal267 - #611~~ By @chienandalu - #732 
- [ ] subcontracted_service
- [ ] vendor_consignment_stock
- [ ] purchase_tier_validation

**Comment by nadiaafa** [comment]
@pedrobaeza i will work on procurement_purchase_no_grouping

**Comment by pedrobaeza** [comment]
@nadiaafa that module can now benefit from hooks that I get into the procurement removal refactoring. Please check them.

**Comment by lukebranch** [comment]
@pedrobaeza ,

I've just upgraded purchase_discount from OCA/purchase-workflow's 10.0 branch with a simple version bump, and product_supplierinfo_discount from Stefan's PR here:
<a href="https://github.com/StefanRijnhart/purchase-workflow/commit/4b6bfad2c0bf81460c8be2ecdabb44e9442f1a83">https://github.com/StefanRijnhart/purchase-workflow/commit/4b6bfad2c0bf81460c8be2ecdabb44e9442f1a83</a>

The only thing i've needed to do is remove procurement.order from ../models/__init__.py and it all works fine for me without additional changes.

Would you accept a PR for the purchase_discount module with a simple version bump, and could you advise the reasons behind the unmerged PR from Stefan for product_supplierinfo_discount if you have time?

This requirement is very common among trading companies (in Hong Kong at least) where the manufacturer or vendor will offer a discount on their list price, and need the discount % as well as the revised subtotal amount shown on the PO and VB lines.

**Comment by pedrobaeza** [comment]
@lukebranch please make a PR following migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 and I'll review both

**Comment by celm1990** [comment]
Hi,
Module purchase_last_price_info is not migrate from V8, I need it for V11, can create PR only V11 or must be V9, V10 and V11???

**Comment by pedrobaeza** [comment]
No, you can go directly to v11, but use the migration guide for preserving commit history the same, but replacing `10.0` references by `8.0`

**Comment by Montxu** [comment]
purchase_order_revision #621

**Comment by emagdalenaC2i** [comment]
@pedrobaeza purchase_delivery_split_date - By @hizbul25 - #511 is closed and superseded By @jbeficent - #584 that is already migrated and merged

purchase_open_qty - By @andreasdsp - #554 is closed and superseded By @mreficent - #602 that is already migrated and merged

Please, check product_supplierinfo_discount - By @DarkoNikolovski - #534 - By @cubells - #592 because it is already merged

Please, add to the list purchase_date_planned_manual - By @lreficent - #597 that is already merged

Please, add to the list purchase_location_by_line - By @hveficent - #604  that is already merged

Please, add to the list purchase_minimum_amount - By @rgarnau - #477  that is already merged

There is a PR for the migration of purchase_order_approval_block - By @jbeficent - #480 

Please, add to the list purchase_order_approved - By @lreficent - #555 that is already merged

There is a PR for the migration of purchase_request - By @jbeficent - #544 
Also purchase_request_procurement and purchase_request_to_rfq are merged into purchase_request  in #544 

Please, add to the list purchase_tier_validation - By @lreficent - #548 that is already merged

Please, add to the list purchase_request_to_rfq_order_approved that is renamed as purchase_request_order_approved - By @hveficent - #599 that is already approved and waiting to be merged

Please, add to the list purchase_request_department - By @hveficent - #598 

purchase_triple_discount - By @krunal267 - #611 There are other PR for the migration of this module #595 

There is a PR for the migration of purchase_all_shipments - By  @mpanarin - #573 

There is a PR for the migration of purchase_last_price_info - By  @celm1990 - #540

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check purchase_order_approval_block - By @jbeficent - #480 because it is already merged
